spring:
  application:
    name: zapret-wrapper
logging:
  level:
    org.example: trace
zapret:
  folder-path: E:\ultra-zapret\zapret-win-bundle-master
  bat-path: E:\ultra-zapret\zapret-win-bundle-master\zapret-winws
  bat-name: OWNBypas.bat
